### PR TITLE
Feature/Material

### PR DESCRIPTION
**Pull request by marywarrington**
@EvanLovely We need to clean up bedrock.config.js in the Bootstrap example — it borks if I remove all assetSets, but since I left one in the demos (specifically Material templates) show the option to choose asset sets.

### CODE REVIEW

**Comment by EvanLovely** [comment]
@marywarrington I've removed the requirement of needing at least 1 global assetSet, so go ahead and try again!

**Comment by EvanLovely** [comment]
And I merged those changes into this branch

**Comment by marywarrington** [comment]
@EvanLovely should be ready to go now!

**Comment by EvanLovely** [comment]
Released in [v0.40.3](https://github.com/basaltinc/bedrock/releases/tag/v0.40.3)

**Pull request merged**
